/*
 * CadastroFuncionarioInterface.java
 *
 * Created on 16/10/2010, 13:23:34
 */
package posto;

//import javax.swing.JOptionPane;
/**
 *
 * @author Ezequiel
 */
public class CadastroFuncionarioInterface extends javax.swing.JFrame {

    /** Creates new form CadastroFuncionarioInterface */
    public CadastroFuncionarioInterface() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private String nomeDoFuncionario, cpf, rg, tipoDoFuncionario, senha, rua, numero, bairro, cidade, telefone, celular, est;
    private UnidadeFederativa estado;
    private boolean v1 = true, v2 = true, v3 = true, v4 = true, v5 = true, v6 = true, v7 = true, v8 = true, v9 = true, v10 = true, v11 = true, v12 = true;
    private static LoginNoSistema log;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("RG:");

        jLabel4.setText("Tipo de Funcionario:");

        jLabel5.setText("Senha:");

        jLabel6.setText("Rua:");

        jLabel7.setText("Número:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("status");

        jLabel9.setText("status");

        jLabel10.setText("status");

        jLabel11.setText("status");

        jLabel12.setText("status");

        jLabel13.setText("status");

        jLabel14.setText("status");

        jLabel16.setText("Bairro:");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel17.setText("status");

        jLabel18.setText("Cidade:");

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jLabel19.setText("status");

        jLabel20.setText("Estado:");

        jLabel21.setText("status");

        jLabel22.setText("Telefone:");

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });

        jLabel23.setText("status");

        jLabel24.setText("Celular:");

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });

        jLabel25.setText("status");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel26.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jComboBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        // verificando autenticidade do cpf
//        if (!verificaCPF(jTextField2.getText()) || jTextField2.getText().equals("CPF invalido.") || jTextField2.getText().equals("")) {
//            jLabel9.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField2.setText("CPF invalido.");
//            v1 = false;
//            jLabel9.setText("ERRO");
//        } else {
//            cpf = jTextField2.getText();
//            jLabel9.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel9.setText("OK");
//        }

//        // Verifica se o nome eh valido
//        if (existeDigito(jTextField1.getText()) || jTextField1.getText().equals("Nome invalido.") || jTextField1.getText().equals("")) {
//            jLabel8.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField1.setText("Nome invalido.");
//            v2 = false;
//            jLabel8.setText("ERRO");
//        } else {
//            nomeDoFuncionario = jTextField1.getText();
//            jLabel8.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel8.setText("OK");
//        }

//        // Verifica se ha caracteres que nao sao digitos no rg
//        if (contaDigitos(jTextField3.getText()) < jTextField3.getText().length() || jTextField3.getText().equals("RG invalido.") || jTextField3.getText().equals("")) {
//            jLabel10.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField3.setText("RG invalido.");
//            v3 = false;
//            jLabel10.setText("ERRO");
//        } else {
//            rg = jTextField3.getText();
//            jLabel10.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel10.setText("OK");
//        }
//        // verificando autenticidade do CNPJ
//        if(!verificaCNPJ(jTextField2.getText())){
//            jTextField2.setText("CNPJ invalido.");
//        } else{
//            cnpj = jTextField2.getText();
//        }
//        // procurando digitos em rua
//        if (existeDigito(jTextField6.getText()) || jTextField6.getText().equals("Nome da rua invalido.") || jTextField6.getText().equals("")) {
//            jLabel13.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField6.setText("Nome da rua invalido.");
//            v4 = false;
//            jLabel13.setText("ERRO");
//        } else {
//            rua = jTextField6.getText();
//            jLabel13.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel13.setText("OK");
//        }
//        // procurando digitos em bairro
//        if (existeDigito(jTextField8.getText()) || jTextField8.getText().equals("Nome do bairro invalido.") || jTextField8.getText().equals("")) {
//            jLabel17.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField8.setText("Nome do bairro invalido.");
//            v5 = false;
//            jLabel17.setText("ERRO");
//        } else {
//            bairro = jTextField8.getText();
//            jLabel17.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel17.setText("OK");
//        }
//        // procurando digitos em cidade
//        if (existeDigito(jTextField9.getText()) || jTextField9.getText().equals("Nome da cidade invalido.") || jTextField9.getText().equals("")) {
//            jLabel19.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField9.setText("Nome da cidade invalido.");
//            v6 = false;
//            jLabel19.setText("ERRO");
//        } else {
//            cidade = jTextField9.getText();
//            jLabel19.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel19.setText("OK");
//        }
//        // procurando caracteres em numero
//        if (contaDigitos(jTextField7.getText()) < jTextField7.getText().length() || jTextField7.getText().equals("Numero invalido.") || jTextField7.getText().equals("")) {
//            jLabel14.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField7.setText("Numero invalido.");
//            v7 = false;
//            jLabel14.setText("ERRO");
//        } else {
//            numero = jTextField7.getText();
//            jLabel14.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel14.setText("OK");
//        }
//        // procurando caracteres em telefone
//        if (contaDigitos(jTextField11.getText()) < jTextField11.getText().length() || jTextField11.getText().equals("Telefone invalido.") || jTextField11.getText().equals("")) {
//            jLabel23.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField11.setText("Telefone invalido.");
//            v8 = false;
//            jLabel23.setText("ERRO");
//        } else {
//            telefone = jTextField11.getText();
//            jLabel23.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel23.setText("OK");
//        }
//        // procurando caracteres em celular
//        if (contaDigitos(jTextField12.getText()) < jTextField12.getText().length() || jTextField12.getText().equals("Celular invalido.") || jTextField12.getText().equals("")) {
//            jLabel25.setForeground(new java.awt.Color(255, 0, 0));
//            jTextField12.setText("Celular invalido.");
//            v9 = false;
//            jLabel25.setText("ERRO");
//        } else {
//            celular = jTextField12.getText();
//            jLabel25.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel25.setText("OK");
//        }
//        // testando senha
//        if (!testaSenha(jTextField5.getText()) || jTextField5.getText().equals("Senha invalida.") || jTextField5.getText().equals("")) {
//            jLabel12.setForeground(new java.awt.Color(255, 0, 0));
//            jLabel12.setText("ERRO");
//            jTextField5.setText("Senha invalida.");
//            v11 = false;
//        } else {
//            senha = jTextField5.getText();
//            jLabel12.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel12.setText("OK");
//        }

//        // verificando tipo do funcionario
//        if (!tipoFuncionario(jTextField4.getText()) || jTextField4.getText().equals("Tipo invalido.") || jTextField4.getText().equals("")) {
//            jTextField4.setText("Tipo invalido.");
//            jLabel11.setForeground(new java.awt.Color(255, 0, 0));
//            jLabel11.setText("ERRO");
//            v12 = false;
//        } else {
//            tipoDoFuncionario = jTextField4.getText();
//            jLabel11.setForeground(new java.awt.Color(0, 153, 0));
//            jLabel11.setText("OK");
//        }

        // tratando estado
//        est = (String) jComboBox1.getSelectedItem();
//        if (!verificaUF(est)) {
//            jLabel21.setForeground(new java.awt.Color(255, 0, 0));
//            //jTextField10.setText("Estado invalido.");
//            jLabel21.setText("ERRO");
//            v10 = false;
//        } else {
//            for (UnidadeFederativa uf : UnidadeFederativa.values()) {
//                if (String.valueOf(uf).equals(est)) {
//                    estado = uf;
//                    //jTextField10.setText(uf.getEstado());
//                    jLabel21.setForeground(new java.awt.Color(0, 153, 0));
//                    jLabel21.setText("OK");
//                }
//            }
//        }

        // Criando objetos e talz...
        if (v1 && v2 && v3 && v4 && v5 && v6 && v7 && v8 && v9 && v10 && v11 && v12) {
            Endereco endereco = new Endereco(estado, rua, numero, bairro, cidade, telefone, celular);
            Pessoa pessoa = new Pessoa(nomeDoFuncionario, cpf, rg);
            CadastroFuncionario funcionario = new CadastroFuncionario(pessoa, endereco, tipoDoFuncionario, senha);
            TodosOsFuncionarios lista = new TodosOsFuncionarios();
            lista.addFuncionario(funcionario);
            log = new LoginNoSistema(lista);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        est = (String) jComboBox1.getSelectedItem();
        if (!verificaUF(est)) {
            jLabel21.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField10.setText("Estado invalido.");
            jLabel21.setText("ERRO");
            jLabel26.setText("");
            v10 = false;
        } else {
            for (UnidadeFederativa uf : UnidadeFederativa.values()) {
                if (String.valueOf(uf).equals(est)) {
                    estado = uf;
                    jLabel26.setText(uf.getEstado());
                    jLabel21.setForeground(new java.awt.Color(0, 153, 0));
                    jLabel21.setText("OK");
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // Verifica se o nome eh valido
        if (existeDigito(jTextField1.getText()) || jTextField1.getText().equals("")) {
            jLabel8.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField1.setText("Nome invalido.");
            v2 = false;
            jLabel8.setText("ERRO");
        } else {
            nomeDoFuncionario = jTextField1.getText();
            jLabel8.setForeground(new java.awt.Color(0, 153, 0));
            jLabel8.setText("OK");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // verificando autenticidade do cpf
        if (!verificaCPF(jTextField2.getText()) || jTextField2.getText().equals("")) {
            jLabel9.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField2.setText("CPF invalido.");
            v1 = false;
            jLabel9.setText("ERRO");
        } else {
            cpf = jTextField2.getText();
            jLabel9.setForeground(new java.awt.Color(0, 153, 0));
            jLabel9.setText("OK");
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // Verifica se ha caracteres que nao sao digitos no rg
        if (contaDigitos(jTextField3.getText()) < jTextField3.getText().length() || jTextField3.getText().equals("")) {
            jLabel10.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField3.setText("RG invalido.");
            v3 = false;
            jLabel10.setText("ERRO");
        } else {
            rg = jTextField3.getText();
            jLabel10.setForeground(new java.awt.Color(0, 153, 0));
            jLabel10.setText("OK");
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // verificando tipo do funcionario
        if (!tipoFuncionario(jTextField4.getText()) || jTextField4.getText().equals("")) {
            //jTextField4.setText("Tipo invalido.");
            jLabel11.setForeground(new java.awt.Color(255, 0, 0));
            jLabel11.setText("ERRO");
            v12 = false;
        } else {
            tipoDoFuncionario = jTextField4.getText();
            jLabel11.setForeground(new java.awt.Color(0, 153, 0));
            jLabel11.setText("OK");
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // testando senha
        if (!testaSenha(jTextField5.getText()) || jTextField5.getText().equals("")) {
            jLabel12.setForeground(new java.awt.Color(255, 0, 0));
            jLabel12.setText("ERRO");
            //jTextField5.setText("Senha invalida.");
            v11 = false;
        } else {
            senha = jTextField5.getText();
            jLabel12.setForeground(new java.awt.Color(0, 153, 0));
            jLabel12.setText("OK");
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // procurando digitos em rua
        if (existeDigito(jTextField6.getText()) || jTextField6.getText().equals("")) {
            jLabel13.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField6.setText("Nome da rua invalido.");
            v4 = false;
            jLabel13.setText("ERRO");
        } else {
            rua = jTextField6.getText();
            jLabel13.setForeground(new java.awt.Color(0, 153, 0));
            jLabel13.setText("OK");
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // procurando caracteres em numero
        if (contaDigitos(jTextField7.getText()) < jTextField7.getText().length() || jTextField7.getText().equals("")) {
            jLabel14.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField7.setText("Numero invalido.");
            v7 = false;
            jLabel14.setText("ERRO");
        } else {
            numero = jTextField7.getText();
            jLabel14.setForeground(new java.awt.Color(0, 153, 0));
            jLabel14.setText("OK");
        }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // procurando digitos em bairro
        if (existeDigito(jTextField8.getText()) || jTextField8.getText().equals("")) {
            jLabel17.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField8.setText("Nome do bairro invalido.");
            v5 = false;
            jLabel17.setText("ERRO");
        } else {
            bairro = jTextField8.getText();
            jLabel17.setForeground(new java.awt.Color(0, 153, 0));
            jLabel17.setText("OK");
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // procurando digitos em cidade
        if (existeDigito(jTextField9.getText()) || jTextField9.getText().equals("")) {
            jLabel19.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField9.setText("Nome da cidade invalido.");
            v6 = false;
            jLabel19.setText("ERRO");
        } else {
            cidade = jTextField9.getText();
            jLabel19.setForeground(new java.awt.Color(0, 153, 0));
            jLabel19.setText("OK");
        }
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // procurando caracteres em telefone
        if (contaDigitos(jTextField11.getText()) < jTextField11.getText().length() || jTextField11.getText().equals("")) {
            jLabel23.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField11.setText("Telefone invalido.");
            v8 = false;
            jLabel23.setText("ERRO");
        } else {
            telefone = jTextField11.getText();
            jLabel23.setForeground(new java.awt.Color(0, 153, 0));
            jLabel23.setText("OK");
        }
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        // procurando caracteres em celular
        if (contaDigitos(jTextField12.getText()) < jTextField12.getText().length() || jTextField12.getText().equals("")) {
            jLabel25.setForeground(new java.awt.Color(255, 0, 0));
            //jTextField12.setText("Celular invalido.");
            v9 = false;
            jLabel25.setText("ERRO");
        } else {
            celular = jTextField12.getText();
            jLabel25.setForeground(new java.awt.Color(0, 153, 0));
            jLabel25.setText("OK");
        }
    }//GEN-LAST:event_jTextField12KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroFuncionarioInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private boolean existeDigito(String nome) {
        for (int i = 0; i < nome.length(); i++) {
            if (nome.charAt(i) >= '0' && nome.charAt(i) <= '9') {
                return true;
            }
        }
        return false;
    }

    // Metodo que conta quantos digitos existem em uma variavel String
    private int contaDigitos(String numero) {
        int contador = 0;
        for (int i = 0; i < numero.length(); i++) {
            if (numero.charAt(i) >= '0' && numero.charAt(i) <= '9') {
                contador++;
            }
        }
        return contador;
    }

    private boolean testaSenha(String senha) {
        int contador = 0;
        for (int i = 0; i < senha.length(); i++) {
            if (senha.charAt(i) >= '0' && senha.charAt(i) <= '9') {
                contador++;
            }
        }
        // pelo menos um numero
        if (contador >= 1) {
            contador = 0;
            for (int i = 0; i < senha.length(); i++) {
                if (senha.charAt(i) >= 'A' && senha.charAt(i) <= 'Z' || senha.charAt(i) >= 'a' && senha.charAt(i) <= 'z') {
                    contador++;
                }
            }
            // pelo menos uma letra
            if (contador >= 1) {
                return true;
            }
        }
        return false;
    }
    // tipos de funcionario

    private boolean tipoFuncionario(String tipoDoFuncionario) {
        if (tipoDoFuncionario.equalsIgnoreCase("Gerente")
                || tipoDoFuncionario.equalsIgnoreCase("Lojista")
                || tipoDoFuncionario.equalsIgnoreCase("Frentista")) {
            return true;
        }
        return false;
    }

    private boolean verificaUF(String estado) {
        for (UnidadeFederativa uf : UnidadeFederativa.values()) {
            if (String.valueOf(uf).equals(estado)) {
                return true;
            }
        }
        return false;
    }

    private boolean verificaCPF(String cpf) {

        int decimo, decimoPrimeiro, soma = 0, mult = 10, resto;
        int cpfInt[] = new int[11];

        if (cpf.length() < 11 || cpf.length() > 11 || contaDigitos(cpf) < 11) {
            return false;
        }

        for (int i = 0; i < 11; i++) {
            cpfInt[i] = Integer.parseInt(String.valueOf(cpf.charAt(i)));
        }

        // Verifica decimo digito
        for (int i = 0; i < 9; i++) {
            soma += (mult * cpfInt[i]);
            mult--;
        }

        resto = soma % 11;
        decimo = (resto == 0 || resto == 1) ? 0 : 11 - resto;

        if (decimo == cpfInt[9]) {

            mult = 11;
            soma = 0;

            // Verifica o decimo-primeiro digito
            for (int i = 0; i < 10; i++) {
                soma += (mult * cpfInt[i]);
                mult--;
            }

            resto = soma % 11;
            decimoPrimeiro = (resto == 0 || resto == 1) ? 0 : 11 - resto;

            if (decimoPrimeiro == cpfInt[10]) {
                return true;
            }

        }

        return false;
    }

    // Metodo que verifica se um CNPJ eh valido a partir da formacao dos dois
    // ultimos digitos
    private boolean verificaCNPJ(String cnpj) {

        int decimoTerceiro, decimoQuarto, soma = 0, mult = 5, resto;
        int cnpjInt[] = new int[14];

        if (cnpj.length() < 14 || cnpj.length() > 14 || contaDigitos(cnpj) < 14) {
            return false;
        }

        for (int i = 0; i < 14; i++) {
            cnpjInt[i] = Integer.parseInt(String.valueOf(cnpj.charAt(i)));
        }

        // Verifica decimo-terceiro digito
        for (int i = 0; i < 12; i++) {
            // System.out.println(mult);
            soma += (mult * cnpjInt[i]);
            mult--;
            mult = mult < 2 ? 9 : mult;
        }

        resto = soma % 11;
        decimoTerceiro = (resto == 0 || resto == 1) ? 0 : 11 - resto;

        if (decimoTerceiro == cnpjInt[12]) {

            mult = 6;
            soma = 0;

            // Verifica o decimo-quarto digito
            for (int i = 0; i < 13; i++) {
                soma += (mult * cnpjInt[i]);
                mult--;
                mult = mult < 2 ? 9 : mult;
            }

            resto = soma % 11;
            decimoQuarto = (resto == 0 || resto == 1) ? 0 : 11 - resto;

            if (decimoQuarto == cnpjInt[13]) {
                return true;
            }
        }

        return false;
    }
}
